import { KIND_LABELS } from "../kinds.mjs";

export const CREATION_COPY = Object.freeze({
  kindLabels: KIND_LABELS,
  choices: Object.freeze({
    value: "Value",
    rule: "Rule",
    clock: "Clock",
    mood: "Mood",
    palette: "Palette",
    identifier: "Identifier"
  }),
  outlineItems: Object.freeze(["Pillar", "Value", "Collection", "Mood", "Palette", "Measured promise", "Clock", "Rule", "Acceptance test", "Question", "Chapter"]),
  createNew: "Create new:",
  as: "as",
  kind: "Kind",
  jsonValue: "JSON value",
  ruleLine: "Rule line",
  ruleFalse: "this rule is false for the current values",
  writeRuleAnyway: "Write it anyway",
  confirm: "Confirm",
  cancelEsc: "Cancel (Esc)",
  createNamed: name => `Create ${name}`,
  useExisting: "Use an existing name:",
  useExistingAction: name => `Use ${name}`,
  citationGone: name => `\`${name}\` is no longer in the text.`,
  cannotCreateHere: name => `Cannot create ${name} here.`,
  alreadyDeclared: name => `\`${name}\` is already declared.`,
  validJsonScalar: "Enter a valid JSON scalar.",
  jsonScalarOnly: "Enter a JSON scalar, not an object or array.",
  cannotAddNoPlan: name => `Cannot add ${name}: this package has no declared writable plan file.`,
  cannotAddExistingHeading: (name, target) => `Cannot add ${name}: ${name} already has a heading in ${target}.`,
  cannotAddNextAcceptance: (name, next) => `Cannot add ${name}: the next acceptance test must be AT-${next}.`,
  createScenarioTest: "Create scenario test",
  createGeneralTest: "Create general test",
  createClock: "Create clock",
  createPalette: "Create palette",
  createValue: "Add a value",
  createSection: "Create section",
  createRule: "Create rule",
  createMood: "Create mood",
  giveSectionHere: "Give it a section here",
  addCollectionRecord: drawer => `Add a record to ${drawer}`,
  more: "More…",
  collectionDialog: Object.freeze({
    title: "Create a collection",
    collectionQuestion: "What are you collecting?",
    collectionHelp: "One word or a few, joined with hyphens — enemies, levels, cards. Your chapters will cite it by this name.",
    collectionPreview: name => `Saved as \`collections/${name}/\``,
    collectionTaken: name => `You already have a collection called \`${name}\`. Pick another name.`,
    firstRecordQuestion: "What's the first one called?",
    skipFirstRecord: "Skip — I'll add records later",
    recordQuestion: "What is this one called?",
    recordHelp: "Lowercase words joined with hyphens — gloom-moth. Prose will cite it by this name.",
    recordPreview: name => `Saved as \`${name}\``,
    recordTaken: (name, collection) => `\`${name}\` is already in ${collection}. Pick another name.`,
    create: "Create",
    cancel: "Cancel",
    createUndo: "Create a collection",
    addRecordUndo: "Add a record"
  }),
  chapterDialog: Object.freeze({
    title: "Add a chapter",
    question: "What is this chapter called?",
    help: "One word or a few; the filename uses lowercase words joined with hyphens.",
    preview: (number, stem) => `Saved as \`${number}-${stem}.md\``,
    nameRequired: "Enter a chapter name.",
    create: "Create",
    cancel: "Cancel",
    createUndo: "Add a chapter"
  }),
  noChapterNumber: "No chapter number from 06 through 99 is available.",
  cannotAddDirectionObject: name => `Cannot add ${name}: direction.json is not a writable object.`,
  cannotAddPaletteObject: name => `Cannot add ${name}: direction.json palette is not a writable object.`,
  cannotAddReserved: name => `Cannot add ${name}: this token is reserved for a mechanism, file, or version reference.`,
  cannotAddTuningObjects: name => `Cannot add ${name}: tuning.json has no writable values object.`,
  cannotAddNoTuning: name => `Cannot add ${name}: this package has no tuning.json.`,
  cannotAddTuningObject: name => `Cannot add ${name}: tuning.json is not a writable object.`,
  cannotAddRulesObject: name => `Cannot add ${name}: tuning.json rules is not a writable object.`,
  cannotAddClocksObject: name => `Cannot add ${name}: clocks.json is not a writable object.`,
  cannotFindClockModes: name => `Cannot add ${name}: the existing clocks do not declare a mode.`,
  cannotRangeValue: name => `Cannot add a range to ${name}: its current value is not a finite number.`,
  rangeRequired: question => `\`${question}\` sets this value; keep the range or change the question`,
  cannotAddMarkdownTarget: name => `Cannot add ${name}: its Markdown target is not uniquely writable.`,
  cannotAddNoMarkdown: name => `Cannot add ${name}: no Markdown chapter is open.`,
  measuredPromiseTypeRequired: "Choose colour, contrast, or timing for the measured promise.",
  measuredPromiseNeedsColor: "Add a named palette colour before creating a colour promise.",
  measuredPromiseNeedsTwoColors: "Add at least two named palette colours before creating a contrast promise.",
  measuredPromiseNeedsTuningKey: "Add a tuning value before creating a timing promise.",
  questionPlaceholderPrompt: "Describe the question the builder should answer.",
  cannotAddNameShape: name => `Cannot add ${name}: a name may contain only letters, numbers, dot, underscore, and hyphen.`,
  addedTo: (name, target) => `Added \`${name}\` to ${target}.`,
  addedPalette: name => `Added \`${name}\` to direction.json palette.`,
  addedValue: name => `Added \`${name}\` to tuning.json values.`,
  addedRule: name => `Added \`rules.${name}\` to tuning.json.`,
  addedClock: name => `Added \`clocks.${name}\` to clocks.json.`,
  addedMood: name => `Added \`${name}\` to direction.json mood.`,
  addedCollection: (name, drawer) => `Added \`${name}\` to collections/${drawer}/.`,
  gaveSection: (name, target) => `Gave \`${name}\` a section in ${target}.`,
  unsupportedOperation: type => `Creation emitted an unsupported ${type} operation.`,
  outlineErrors: Object.freeze({
    tuningObject: "tuning.json values must be an object.",
    rangesObject: "tuning.json ranges must be an object.",
    moodDirection: "direction.json is required to create a mood.",
    moodsObject: "direction.json mood must be an object.",
    paletteDirection: "direction.json is required to create a palette.",
    paletteObject: "direction.json palette must be an object.",
    pillarsObject: "direction.json pillars must be an object.",
    personalizationObject: "personalization.json must be a JSON object.",
    personalizationQuestions: "personalization.json questions must be an array.",
    promiseDirection: "direction.json must contain a JSON object to create a measured promise.",
    promiseMap: kind => `direction.json ${kind} must be an object.`
  })
});
