import { KIND_LABELS } from "../kinds.mjs";

const location = (file, line) => `${file}, line ${line}`;

export const INSPECTOR_COPY = Object.freeze({
  showInFile: file => `Show in ${file}`,
  rename: "Rename",
  remove: "Remove",
  cancel: "Cancel",
  more: "More",
  none: "none",
  required: "required",
  locationName: location,
  locationDetail: location,
  entityKind: kind => KIND_LABELS[kind] ?? kind,
  entityName: (name, kind) => `${name}, ${kind}`,
  citations: "Citations",
  citationsHelp: "Choose a citation to open its source passage.",
  findings: "Problems",
  unreadable: "This file is not valid JSON yet. Fix it in the editor before using structured fields.",
  mechanismTitle: "Mechanism",
  mechanismKind: "mechanism",
  mechanismDeclarations: "Declarations",
  mechanismDeclarationsHelp: "Choose a declaration to inspect it.",
  mechanismNoDeclarations: "This mechanism has no declarations yet.",
  tuningEmpty: "Choose Tuning in the outline to inspect it.",
  tuningValues: "Values",
  tuningValuesHelp: "Choose a value to inspect its current number and optional inclusive range.",
  tuningValueDetail: (value, range) => `${value}${range ? ` · ${range[0]}–${range[1]}` : ""}`,
  newValue: "New value",
  newValueHelp: "Add a named number that the design and build can share.",
  newRule: "New rule",
  newRuleHelp: "Add one readable comparison that keeps tuning values in step.",
  tuningValueTitle: "Value",
  tuningValueEmpty: "Choose a tuning value in the outline to inspect it.",
  tuningValueKind: "tuning value",
  tuningValue: "Value",
  tuningValueHelp: "Enter the finite number the design and build read for this key.",
  tuningFiniteNumber: "Enter a finite number.",
  tuningRange: "Range",
  tuningMinimum: "Minimum",
  tuningMinimumHelp: "Enter the lowest inclusive value a rebalance or personalization answer may use.",
  tuningMaximum: "Maximum",
  tuningMaximumHelp: "Enter the highest inclusive value a rebalance or personalization answer may use.",
  tuningRangeOrder: (minimum, maximum) => `The minimum ${minimum} must not exceed the maximum ${maximum}.`,
  tuningValueOutside: (value, minimum, maximum) => `The value ${value} must stay inside the inclusive range ${minimum} to ${maximum}.`,
  addTuningRange: "Add range",
  tuningAddRangeHelp: "Make this value movable by adding an inclusive range at its current number.",
  removeTuningRange: "Remove range",
  tuningRemoveRangeHelp: "Remove this value's inclusive range so the number is fixed as written.",
  addTuningRangeUndo: "Add a range",
  removeTuningRangeUndo: "Remove the range",
  changeTuningValue: "Change a tuning value",
  changeTuningRange: "Change a tuning range",
  tuningRulesReadingValue: "Read by rules",
  tuningRulesReadingValueHelp: "Each row shows the authored rule line and whether it holds for the current values.",
  tuningNoRulesReadValue: "No tuning rule reads this value.",
  tuningRuleDetail: (line, verdict) => `${line ? `line ${line} · ` : ""}${verdict}`,
  tuningQuestionsSettingValue: "Set by questions",
  tuningQuestionsSettingValueHelp: "These questions may set this value during the ordered package-default pipeline.",
  tuningNoQuestionsSetValue: "No personalization question sets this value.",
  tuningTimingPromises: "Timing promises",
  tuningTimingPromisesHelp: "These Direction timing promises require a rendered event to match this value.",
  tuningNoTimingPromises: "No timing promise names this value.",
  tuningCitations: "Cited in",
  tuningCitationsHelp: "Choose a citation to open the chapter passage that uses this value.",
  tuningNoCitations: "No chapter cites this value.",
  tuningContracts: "Used by contracts",
  tuningContractsHelp: "Changing this number affects every listed contract setting. Choose a use to see its source.",
  removeTuningValueQuestion: (name, dependencies) => {
    const parts = [];
    if (dependencies.citations.length) parts.push(`${dependencies.citations.length} prose ${dependencies.citations.length === 1 ? "citation" : "citations"}`);
    if (dependencies.rules.length) parts.push(`rules ${dependencies.rules.map(rule => `\`${rule}\``).join(", ")}`);
    if (dependencies.questions.length) parts.push(`questions ${dependencies.questions.map(question => `\`${question}\``).join(", ")}`);
    if (dependencies.promises.length) parts.push(`timing ${dependencies.promises.map(promise => `\`${promise}\``).join(", ")}`);
    if (dependencies.contracts?.length) parts.push(`${dependencies.contracts.length} contract ${dependencies.contracts.length === 1 ? "setting" : "settings"}`);
    const range = dependencies.range ? " Its range will be removed too." : "";
    const remaining = parts.length ? ` This will leave ${parts.join("; ")} pointing at a missing value.` : "";
    return `Remove ${name}?${range}${remaining}`;
  },
  tuningRuleTitle: "Rule",
  tuningRuleEmpty: "Choose a tuning rule in the outline to inspect it.",
  tuningRuleKind: "tuning rule",
  tuningProseRuleKind: "prose rule heading",
  tuningProseRuleEmpty: name => `${name} is a prose rule heading, so it has no tuning.json rule line to edit here.`,
  tuningRuleLine: "Rule line",
  tuningRuleLineHelp: "Write one comparison between two arithmetic sums over declared tuning values.",
  changeTuningRule: "Change a tuning rule",
  tuningRuleReads: "Reads values",
  tuningRuleReadsHelp: "These are the current authored numbers used when the rule is evaluated.",
  tuningRuleReadsNone: "This rule line does not read a tuning value.",
  tuningRuleHolds: "holds",
  tuningRuleFails: "fails",
  tuningRuleInvalid: "invalid",
  removeTuningRuleQuestion: (name, citations) => citations
    ? `Remove ${name}? ${citations} prose ${citations === 1 ? "citation will" : "citations will"} point at a missing rule.`
    : `Remove ${name}?`,
  tuningRules: "Rules",
  tuningRulesHelp: "Choose a rule to inspect its line, current values, and verdict.",
  tuningNoRules: "No tuning rules yet.",
  clockTitle: "Clock",
  clockEmpty: "Choose a clock in the outline to inspect it.",
  clockKind: "clock",
  clockUnit: "Unit",
  clockUnitHelp: "Every clock must declare unit as a non-empty string.",
  clockAdvances: "Advances",
  clockAdvancesHelp: "These runtime addresses are carried forward by this clock. Different clocks' advances lists must be disjoint.",
  clockAdvance: "Runtime value",
  clockAdvanceHelp: "Choose a runtime address declared by chapter use or already named by a clock.",
  clockAdvanceRow: (index, address) => `Runtime value ${index + 1}, ${address}`,
  clockAdvanceLabel: index => `Runtime value ${index + 1}`,
  clockRuntimeCandidates: "Runtime values",
  changeClockAdvance: "Change a clock's runtime value",
  addClockAdvance: "Add runtime value",
  addClockAdvanceHelp: "Append the first runtime address this clock does not already advance, then choose the address you need.",
  addClockAdvanceUndo: "Add a runtime value to a clock",
  removeClockAdvanceUndo: "Remove a runtime value from a clock",
  removeClockAdvanceLabel: address => `Remove ${address} from this clock`,
  clockNoRuntimeToAdd: "Every known runtime value is already in this clock's advances list.",
  clockAdvancesUnreadable: "This clock's advances value is not an array. Fix it in the editor before adding a row.",
  clockAdvanceWithoutModes: "This clock has no modes map. Fix it in the editor before adding a runtime value.",
  otherClockAdvances: entries => `Other clocks already advance ${entries.map(entry => `${entry.address} (${entry.name})`).join(", ")}.`,
  noOtherClockAdvances: "No other clock advances a runtime value.",
  clockModes: "Modes",
  clockModesHelp: "Every clock must name every mode in the union across all clocks.",
  clockModeRow: mode => `Mode ${mode}`,
  clockModeHelp: "Choose running, paused, steps, or none for this clock in this mode.",
  changeClockMode: "Change a clock mode",
  addClockMode: "Add mode",
  addClockModeHelp: "Add a lowercase kebab-case mode to this clock as none. Other clocks are left unchanged and will show their missing cells.",
  clockModeQuestion: "What lowercase kebab-case mode id do you want to add?",
  clockModeIdHelp: "Use lowercase words separated by single hyphens.",
  clockModeIdInvalid: "Use lowercase kebab-case, with letters or numbers on both sides of each hyphen.",
  clockModeTaken: mode => `${mode} is already a declared mode. Use its empty row on this clock instead.`,
  clockModesUnreadable: "This clock's modes value is not an object. Fix it in the editor before adding a mode.",
  addClockModeUndo: "Add a clock mode",
  removeClockModeUndo: "Remove a clock mode",
  removeClockModeLabel: mode => `Remove mode ${mode} from this clock`,
  clockRuntimeValues: "Runtime values",
  clockRuntimeValuesHelp: "Each row opens the first place that declares the runtime value, in a chapter or this clock's advances list.",
  clockNoRuntimeValues: "This clock does not advance a runtime value.",
  clockCitations: "Cited in",
  clockCitationsHelp: "Choose a citation to open the chapter passage that uses this clock.",
  clockNoCitations: "No chapter cites this clock.",
  removeClockQuestion: (name, advances, citations) => {
    const runtime = advances.length ? ` It advances ${advances.map(address => `\`${address}\``).join(", ")}.` : "";
    const prose = citations.length ? ` Prose citations of \`clocks.${name}\`: ${citations.map(site =>
      `${site.file}, line ${(site.range?.start?.line ?? 0) + 1}`).join(", ")}.` : "";
    return `Remove ${name}?${runtime}${prose}`;
  },
  newClock: "New clock",
  newClockHelp: "Add a named source of advance with every existing mode set to none.",
  timeRuntimeValues: "Runtime values",
  timeRuntimeValuesHelp: "Every runtime value declared by chapter use or a clock's advances list stays visible, including one no clock advances.",
  timeNoRuntimeValues: "No chapter use or clock advances list declares a runtime value.",
  timeRuntimeDetail: (clocks, file, line) => `${clocks.length ? clocks.join(", ") : "no clock advances it"} · ${file}, line ${line}`,
  directionPillars: "Pillars",
  directionPillarsHelp: "Put the strongest visual priority first. When two direction goals pull against each other, the earlier pillar wins.",
  directionPillarName: "Pillar name",
  directionPillarNameHelp: "Use a short lowercase-hyphen name that prose can cite.",
  directionPillarSentence: "Priority",
  directionPillarSentenceHelp: "State the visual priority as a complete sentence a builder can act on.",
  directionAnti: "Anti-references",
  directionAntiHelp: "Name visual results the finished game must avoid.",
  directionAntiName: "Anti-reference name",
  directionAntiNameHelp: "Use a short lowercase-hyphen name that prose can cite.",
  directionAntiSentence: "Must not be",
  directionAntiSentenceHelp: "Describe the nearby but wrong result to avoid.",
  directionAntiImage: "Reference image",
  directionAntiImageHelp: "Use a package-relative path to an image that shows what to avoid. An image must have a licence.",
  directionAntiLicense: "Image licence",
  directionAntiLicenseHelp: "Name the licence or permission that allows this reference image to travel with the package.",
  directionMustKeep: "Must keep",
  directionMustKeepHelp: "Record visible qualities that every faithful build must preserve.",
  directionMustKeepName: "Quality name",
  directionMustKeepNameHelp: "Use a short lowercase-hyphen name that prose can cite.",
  directionMustKeepSentence: "Quality",
  directionMustKeepSentenceHelp: "State the visible quality that must survive every implementation.",
  directionViewing: "Viewing",
  directionViewingHelp: "Record the speed, framing, calibration, and optional sequence used to judge the finished result.",
  directionSpeedAndSize: "Speed and size",
  directionSpeedAndSizeHelp: "Say the playback speed and the size or framing at which the result is judged.",
  directionCalibration: "Calibration",
  directionCalibrationHelp: "Say which display or output calibration the judgment assumes.",
  directionSequence: "Sequence",
  directionSequenceHelp: "Optionally name the span or order of play that must be seen. Clear this field to remove it.",
  directionOwned: "Direction items",
  directionOwnedHelp: "Choose one of these independently editable Direction items to inspect it.",
  directionNoOwned: "No moods, palettes, or measured promises yet.",
  newMood: "New mood",
  newMoodHelp: "Add a named feeling with its intended effect and negative space.",
  newPalette: "New palette",
  newMeasuredPromise: "New measured promise",
  newMeasuredPromiseHelp: "Add a measured colour, contrast, or timing promise to Direction.",
  measuredPromiseTypeQuestion: "Which kind of measured promise do you want to add?",
  measuredPromiseColorChoice: "Colour",
  measuredPromiseContrastChoice: "Contrast",
  measuredPromiseTimingChoice: "Timing",
  addPillar: "Add pillar",
  addPillarUndo: "Add a pillar",
  removePillarUndo: "Remove a pillar",
  movePillarUndo: "Move a pillar",
  renamePillarCitations: count => `${count} ${count === 1 ? "citation" : "citations"}`,
  addAnti: "Add anti-reference",
  addAntiHelp: "Append an empty anti-reference and describe the result to avoid.",
  addAntiUndo: "Add an anti-reference",
  removeAntiUndo: "Remove an anti-reference",
  moveAntiUndo: "Move an anti-reference",
  antiUseImage: "Add image and licence",
  antiUseSentence: "Use sentence only",
  convertAntiToObjectUndo: "Add an anti-reference image",
  convertAntiToSentenceUndo: "Remove an anti-reference image",
  addMustKeep: "Add quality",
  addMustKeepUndo: "Add a must-keep quality",
  removeMustKeepUndo: "Remove a must-keep quality",
  moveMustKeepUndo: "Move a must-keep quality",
  listMoveUp: "Up",
  listMoveDown: "Down",
  listRemove: "Remove",
  listMoveUpLabel: label => `Move ${label} up`,
  listMoveDownLabel: label => `Move ${label} down`,
  listRemoveLabel: label => `Remove ${label}`,
  listConvertLabel: (action, label) => `${action} for ${label}`,
  directionListNameInvalid: "Use a lowercase-hyphen name with at least one letter; do not use dots, json, or md.",
  moodTitle: "Mood",
  moodEmpty: "Choose a mood in the outline to inspect it.",
  moodKind: "mood",
  moodIntent: "Intent",
  moodIntentHelp: "Describe the feeling this mood should create for the player.",
  moodAnti: "Anti-references",
  moodAntiHelp: "Keep at least one nearby but wrong feeling visible so the result does not drift toward it.",
  moodAntiRow: index => `Anti-reference ${index + 1}`,
  moodBorrows: "Borrowed references",
  moodBorrowsHelp: "Add sources worth borrowing from and list only the qualities the design should carry across.",
  moodBorrowFrom: "From",
  moodBorrowFromHelp: "Name the source or reference being borrowed from.",
  moodBorrowWhat: "What to borrow",
  moodBorrowWhatHelp: "Put one borrowed quality on each line.",
  moodBorrowImage: "Image",
  moodBorrowImageHelp: "Optionally use a package-relative reference image path. An image requires a licence.",
  moodBorrowLicense: "Licence",
  moodBorrowLicenseHelp: "Name the licence or permission for the reference image.",
  moodPalette: "Palette",
  moodPaletteHelp: "Optionally choose one declared palette for this mood. A colour address cannot stand in for a palette.",
  moodPaletteGroup: "Palettes",
  moodCitations: "Cited in",
  moodCitationsHelp: "Choose a citation to open the chapter passage that uses this mood.",
  moodNoCitations: "No chapter mentions this mood.",
  removeMoodQuestion: (name, count) => count
    ? `Remove ${name}? ${count} ${count === 1 ? "citation will" : "citations will"} remain as ${count === 1 ? "a problem" : "problems"} to fix.`
    : `Remove ${name}?`,
  changeDirectionSentence: "Change a direction sentence",
  changeAntiField: "Change an anti-reference",
  changeViewingField: "Change a viewing condition",
  changeMoodField: "Change a mood field",
  addBorrowUndo: "Add a borrowed reference",
  removeBorrowUndo: "Remove a borrowed reference",
  paletteTitle: "Palette",
  paletteEmpty: "Choose a palette in the outline to inspect it.",
  paletteKind: "palette",
  newPaletteHelp: "Add a named palette to Direction with one ready-to-edit colour.",
  paletteName: "Name",
  paletteNameHelp: "Name a colour only when another part of the design needs to cite it. Clear the name to keep it unaddressed.",
  paletteNameInvalid: "Use a lowercase-hyphen name with at least one letter; do not use dots, json, or md.",
  paletteHex: "Hex colour",
  paletteSwatch: "Swatch",
  paletteHexHelp: "Enter # followed by six hexadecimal digits. Your uppercase or lowercase spelling is kept.",
  paletteHexInvalid: "Enter # followed by exactly six hexadecimal digits.",
  paletteColorLabel: (name, index, hex) => name ? `Colour ${name}` : `Colour ${index + 1}, ${hex}`,
  paletteNameLabel: colour => `Name for ${colour.toLowerCase()}`,
  paletteHexLabel: colour => `Hex colour for ${colour.toLowerCase()}`,
  addColor: "Add colour",
  addColorHelp: "Append an unnamed black colour to this palette.",
  removeColor: "Remove",
  moveColorUp: "Up",
  moveColorDown: "Down",
  removeColorLabel: colour => `Remove ${colour.toLowerCase()}`,
  moveColorUpLabel: colour => `Move ${colour.toLowerCase()} up`,
  moveColorDownLabel: colour => `Move ${colour.toLowerCase()} down`,
  nameColor: "Name a colour",
  unnameColor: "Clear a colour name",
  changeColor: "Change a colour",
  usesPalette: "Used by",
  usesPaletteHelp: "Choose a mood or direction promise to inspect where this palette is used.",
  paletteUnused: "No mood or direction promise uses this palette.",
  removePaletteQuestion: (name, uses, citations) => {
    const referenceText = `${citations} ${citations === 1 ? "reference" : "references"}`;
    return uses.length
      ? `Remove ${name}? ${referenceText} and ${uses.join(", ")} will still cite colours or the palette and will become problems to fix.`
      : citations ? `Remove ${name}? ${referenceText} will remain as ${citations === 1 ? "a problem" : "problems"} to fix.`
        : `Remove ${name}?`;
  },
  changeField: "Change an inspector field",
  undoRename: "Rename an inspector entity",
  removeEntity: label => `Remove ${label}`,
  addColorUndo: "Add a colour",
  removeColorUndo: "Remove a colour",
  moveColorUndo: "Move a colour",
  directionPromiseTitle: "Measured promise",
  directionPromiseEmpty: "Choose a measured promise in the outline to inspect it.",
  promiseColorKind: "colour promise",
  promiseContrastKind: "contrast promise",
  promiseTimingKind: "timing promise",
  promiseColorTarget: "Colour target",
  promiseColorTargetHelp: "Choose the named palette colour this promise requires.",
  promiseColorCandidates: "Named palette colours",
  promiseWithin: "Tolerance",
  promiseWithinHelp: "Set the non-negative CIEDE2000 distance in CIELAB D65. Zero requires the exact declared colour.",
  promiseWithinInvalid: "Enter a tolerance of zero or more.",
  promiseContrastColour: "Colour",
  promiseContrastColor: index => `Colour ${index + 1}`,
  promiseContrastColorLabel: index => `Colour, colour ${index + 1}`,
  promiseContrastColorHelp: "Choose a named palette colour that must meet the minimum contrast ratio.",
  promiseAgainst: "Against",
  promiseAgainstHelp: "Choose the named palette colour each operand is measured against.",
  promiseAtLeast: "Minimum ratio",
  promiseAtLeastHelp: "Enter the positive WCAG 2.1 contrast ratio every colour must meet against the background colour.",
  promiseAtLeastInvalid: "Enter a contrast ratio greater than zero.",
  promiseTimingKey: "Tuning value",
  promiseTimingKeyHelp: "Choose the tuning value whose duration the rendered event must match.",
  promiseTimingCandidates: "Tuning values",
  promiseTimingValue: value => `Current value: ${value}`,
  promiseTimingValueRange: (value, minimum, maximum) => `Current value: ${value}. Range: ${minimum} to ${maximum}.`,
  promiseWhere: "Where",
  promiseWhereHelp: "Name the visible things or rendered event this promise covers.",
  promiseWherePlaceholder: "Describe where this promise applies.",
  promiseWhile: "While",
  promiseWhileHelp: "Optionally put one non-empty state description on each line to say when the promise holds.",
  promiseCoverage: "Covered by tests",
  promiseCoverageHelp: "These game-local acceptance tests cite this measured promise through direction_claims.",
  promiseCoverageLabel: (test, title) => title ? `${test}: ${title}` : test,
  promiseUncovered: address => `No acceptance test's direction_claims cites ${address}. The validator reports DIRECTION_CLAIM_UNCOVERED.`,
  promiseAddColor: "Add colour",
  promiseAddColorHelp: "Append one named palette-colour operand to this contrast promise.",
  promiseAddColorUndo: "Add a contrast colour",
  promiseRemoveColor: "Remove",
  promiseRemoveColorLabel: index => `Remove colour ${index + 1}`,
  promiseRemoveColorUndo: "Remove a contrast colour",
  changeDirectionPromise: "Change a measured promise",
  removeDirectionPromiseQuestion: (name, tests, citations) => {
    const coverage = tests.length ? ` Acceptance tests ${tests.join(", ")} name it in direction_claims and will become problems to fix.` : "";
    const prose = citations ? ` ${citations} ${citations === 1 ? "other reference will" : "other references will"} remain as ${citations === 1 ? "a problem" : "problems"} to fix.` : "";
    return `Remove ${name}?${coverage}${prose}`;
  },
  removeQuestion: (label, count) => count
    ? `Remove ${label}? ${count} references will remain as problems to fix.`
    : `Remove ${label}?`,
  stagedFindingsUnavailable: "Staged validation did not return its introduced findings.",
  renameComplete: (name, next, prose, json) => `Rename \`${name}\` to \`${next}\` in ${prose} prose sites and ${json} JSON sites.`,
  renamePartial: (name, prose, json) => `Only ${prose} prose sites and ${json} JSON sites for \`${name}\` can be named. References declared by prose use may remain.`,
  renameTaken: name => `A declaration named \`${name}\` already exists.`,
  renameName: "Use a name that matches the declaration's address family.",
  renameHeadingEditRefused: "This rename plan cannot edit that section heading.",
  embeddedInvalid: "The fenced block is not valid JSON yet.",
  embeddedRefresh: "Refresh the fenced block before editing it.",
  sectionTitle: "Section",
  sectionEmpty: "Choose a section in the outline to inspect it.",
  sectionKind: "section",
  sectionRemoveHelp: "A section is prose, so remove it in the editor if you no longer need it.",
  sectionHeading: "Heading text",
  sectionHeadingHelp: "Edit the words in this heading. Its level, time-mode tag, and stable anchor stay in place.",
  sectionHeadingRequired: "Enter non-empty heading text.",
  changeSectionHeading: "Change a section heading",
  sectionAnchor: "Anchor slug",
  sectionAnchorHelp: "This lowercase-hyphen slug is the stable destination used by section citations.",
  sectionAnchorInvalid: "Use lowercase words separated by single hyphens.",
  renameSectionAnchor: "Rename a section anchor",
  makeAnchorExplicit: "Make the anchor explicit",
  makeAnchorExplicitUndo: "Make a section anchor explicit",
  sectionFacts: "Facts",
  sectionFactsHelp: "These facts describe where the section sits; edit the source file to change its level or location.",
  sectionLevel: "Heading level",
  sectionFile: "File",
  sectionRulesets: "Rulesets",
  rulesetKind: "ruleset",
  sectionRulesetsHelp: "These RULESET tags divide this section's prose. The package's initial ruleset is listed first.",
  sectionNoRulesets: "No RULESET tag scopes prose inside this section.",
  sectionRulesetLabel: (id, initial) => initial ? `${id}, initial` : id,
  sectionTimeMode: "Time mode",
  sectionTimeModeHelp: "A bracketed tag at the end of the heading scopes this section to one declared time mode.",
  sectionNoTimeMode: "This section applies in every time mode.",
  sectionCitations: "Cited in",
  sectionCitationsHelp: "Choose a citation to open the passage that points here.",
  sectionNoCitations: "No package citation points to this section.",
  sectionRenameQuestion: "What should the new heading text be?",
  renameSection: (slug, next, citations) => `Rename section anchor \`${slug}\` to \`${next}\` and update ${citations} ${citations === 1 ? "citation" : "citations"}.`,
  acceptanceTestTitle: "Acceptance test",
  acceptanceTestEmpty: "Choose an acceptance test in the outline to inspect it.",
  acceptanceTestKind: "acceptance test",
  newAcceptanceTest: "New acceptance test",
  newAcceptanceTestHelp: "Open the build plan's existing acceptance-test creation path.",
  testRenameQuestion: "What should the acceptance-test heading say after its number?",
  testHeadingRequired: "Enter a non-empty acceptance-test heading title.",
  testBlockMissing: "This acceptance-test heading is not followed by a fenced test JSON descriptor.",
  renameAcceptanceTest: "Rename an acceptance test",
  removeAcceptanceTestQuestion: (id, citations) => citations.length
    ? `Remove ${id} and its test block? Prose citations remain at ${citations.map(site => `${site.file}, line ${(site.range?.start?.line ?? 0) + 1}`).join(", ")}.`
    : `Remove ${id} and its test block?`,
  testType: "Test type",
  testTypeHelp: "Choose scenario for one specific situation or general for a claim over many cases.",
  changeTestType: "Change an acceptance-test type",
  changeAcceptanceTest: "Change an acceptance test",
  testStepLabel: key => ({ given: "Given", when: "When", then: "Then" })[key],
  testStepHelp: key => ({
    given: "Put each starting condition on its own line.",
    when: "Put each action or event the runner performs on its own line.",
    then: "Put each expected result on its own line."
  })[key],
  testGeneralLabel: key => key === "scope" ? "Scope" : "Holds",
  testGeneralHelp: key => key === "scope"
    ? "Describe in words the cases this general claim covers."
    : "State the claim that must hold across the named scope.",
  testSeeds: "Seeds",
  testSeedsHelp: "Optionally put one repeatable random seed on each line.",
  testDiagnostics: "Diagnostics",
  testDiagnosticsHelp: "Optionally put one runner diagnostic name on each line.",
  testDirectionClaims: "Direction claims",
  testDirectionClaimsHelp: "Add measured colour, contrast, or timing promises this test covers.",
  testDirectionClaim: "Direction promise",
  testDirectionClaimHelp: "Choose one declared colors, contrast, or timing address.",
  testDirectionClaimRow: index => `Direction promise ${index + 1}`,
  testDirectionCandidates: "Measured direction promises",
  testModes: "Unchanged modes",
  testModesHelp: "Add each declared time mode during which the named runtime values must stay unchanged.",
  testMode: "Mode",
  testModeHelp: "Choose one mode id declared by a clock.",
  testModeRow: index => `Unchanged mode ${index + 1}`,
  testModeCandidates: "Declared modes",
  testRuntimeValues: "Unchanged runtime values",
  testRuntimeValuesHelp: "Add each runtime address that must stay unchanged in the selected modes.",
  testRuntimeValue: "Runtime value",
  testRuntimeValueHelp: "Choose one runtime address declared by chapter use or a clock.",
  testRuntimeRow: index => `Unchanged runtime value ${index + 1}`,
  testRuntimeCandidates: "Runtime values",
  testRemoveRow: "Remove",
  testRemoveRowLabel: value => `Remove ${value}`,
  testAddRow: family => ({ direction_claims: "Add direction claim", modes: "Add mode", values: "Add runtime value" })[family],
  testAddRowUndo: family => ({ direction_claims: "Add a direction claim", modes: "Add an unchanged mode", values: "Add an unchanged runtime value" })[family],
  testRemoveRowUndo: family => ({ direction_claims: "Remove a direction claim", modes: "Remove an unchanged mode", values: "Remove an unchanged runtime value" })[family],
  testListUnreadable: family => `The ${family} value is not an array. Fix it in the editor before adding a row.`,
  testNoReferenceCandidates: family => `There is no declared value available to add to ${family}.`,
  testTarget: "Target",
  testTargetHelp: "Optionally enter the expected numeric observation.",
  testTolerance: "Tolerance",
  testToleranceHelp: "Optionally enter a finite numeric tolerance for the target.",
  testOpaqueLabel: key => key === "replay" ? "Replay JSON" : "Extensions JSON",
  testOpaqueHelp: key => key === "replay"
    ? "Enter the runner-owned replay object as JSON. The core keeps its nested content opaque."
    : "Enter the package-local extension object as JSON. Each top-level extension id owns an object value.",
  testCitations: "Citations",
  testCitationsHelp: "Choose a citation to open the passage that names this acceptance test.",
  testNoCitations: "No prose citation names this acceptance test.",
  testPromises: "Covered promises",
  testPromisesHelp: "Choose a direction promise to open its inspector.",
  testNoPromises: "This test does not cite a measured direction promise.",
  questionTitle: "Question",
  questionEmpty: "Choose a personalization question in the outline to inspect it.",
  questionKind: "question",
  newQuestion: "New question",
  newQuestionHelp: "Add a valid text question to the end of the ordered Personalization list.",
  questionPrompt: "Prompt",
  questionPromptHelp: "Write the non-empty question exactly as the builder should be asked it.",
  questionType: "Question type",
  questionTypeHelp: "Choose choice for named options, text for a written answer, or number for a numeric answer.",
  questionDefault: "Default answer",
  questionDefaultHelp: "Set the answer used when a build skips this question. Clear it to remove the member and show the validator's missing-default problem.",
  questionNotes: "Notes",
  questionNotesHelp: "Optionally give the builder concrete instructions for interpreting the answer. Clear the field to remove it.",
  questionChoiceCandidates: "Options in this question",
  questionNumberTarget: "Number target",
  questionNumberTargetHelp: "Optionally choose the one ranged tuning key that receives the numeric answer. Clear it to keep the answer as creative instruction only.",
  questionRangedCandidates: "Ranged tuning values",
  questionRangeStatus: (minimum, maximum) => `Inclusive range: ${minimum} to ${maximum}.`,
  questionTuningKeys: "Moves keys",
  questionTuningKeysHelp: "Choose a tuning key to open its Value inspector.",
  questionNoTuningKeys: "This question moves no tuning values.",
  questionCitations: "Cited in",
  questionCitationsHelp: "Choose a citation to open the passage that names this question.",
  questionNoCitations: "No prose citation names this question.",
  questionOptions: "Options",
  questionOptionsHelp: "Choice options are applied by id; an option may set any number of ranged tuning values.",
  questionOptionId: "Option id",
  questionOptionIdHelp: "Use lowercase words separated by single hyphens. Renaming the default option moves the default in the same change.",
  questionOptionLabel: "Label",
  questionOptionLabelHelp: "Write the non-empty label shown for this option.",
  questionOptionNotes: "Notes",
  questionOptionNotesHelp: "Optionally give concrete instructions for this answer. Clear the field to remove it.",
  questionOptionSetKey: "Tuning value",
  questionOptionSetKeyHelp: "Choose a ranged tuning key this option sets.",
  questionOptionSetValue: "Number",
  questionOptionSetValueHelp: "Enter the exact number this option assigns; it must stay inside the key's inclusive range.",
  questionOptionRow: (index, id) => `Option ${index + 1}, ${id}`,
  questionSetRow: (option, key) => `${option}, sets ${key}`,
  questionOptionIdInvalid: "Use lowercase kebab-case, with letters or numbers on both sides of each hyphen.",
  questionOptionTaken: id => `This question already has an option called ${id}.`,
  questionOptionTargetGone: "The question or option this rename targeted is gone; reopen the question before trying again.",
  addQuestionOption: "Add option",
  addQuestionOptionHelp: "Append an option with a free kebab-case id and an empty required label for you to complete.",
  addQuestionSet: "Add tuning value",
  addQuestionSetHelp: "Append the first ranged tuning key this option does not already set, using its current authored value.",
  noQuestionSetCandidate: "Every ranged tuning value is already set by this option.",
  questionOptionsUnreadable: "This question's options value is not an array. Fix it in the editor before adding an option.",
  questionSetsUnreadable: "This option's sets value is not an object. Fix it in the editor before adding a tuning value.",
  questionTypeChange: "Change a question type",
  questionTypeConfirmation: members => `Change the question type and remove ${members.join(" and ")}?`,
  questionTypeOptionsMember: "its options",
  questionTypeSetsMember: "its number target",
  changeQuestion: "Change a personalization question",
  changeQuestionOption: "Change a question option",
  changeQuestionSet: "Change an option's tuning value",
  addQuestionOptionUndo: "Add a question option",
  removeQuestionOptionUndo: "Remove a question option",
  moveQuestionOptionUndo: "Move a question option",
  addQuestionSetUndo: "Add an option tuning value",
  removeQuestionSetUndo: "Remove an option tuning value",
  renameQuestionOptionUndo: "Rename a question option",
  moveQuestionUndo: "Move a personalization question",
  removeQuestionQuestion: (id, citations, keys) => {
    const prose = citations.length ? ` Prose citations remain at ${citations.map(site => `${site.file}, line ${(site.range?.start?.line ?? 0) + 1}`).join(", ")}.` : "";
    const tuning = keys.length ? ` This question moves ${keys.map(key => `\`${key}\``).join(", ")}.` : "";
    return `Remove ${id}?${prose}${tuning}`;
  },
  personalizationQuestions: "Questions",
  personalizationQuestionsHelp: "Answers are applied from the first row to the last, so later questions can replace numbers set earlier.",
  personalizationQuestionRow: (_id, prompt, type, keys) => `${prompt} · ${type}${keys.length ? ` · moves ${keys.join(", ")}` : " · moves no tuning keys"}`,
  personalizationNoQuestions: "No personalization questions yet."
});
