import { entityKindsForMechanism } from "../kinds.mjs";
import { CONTRACT_COPY } from "./contract-copy.mjs";
import { INSPECTOR_COPY } from "./inspector-copy.mjs";

const outlineMechanism = definition => Object.freeze({
  ...definition,
  kinds: entityKindsForMechanism(definition.id)
});

const OUTLINE_MECHANISMS = Object.freeze(Object.fromEntries([
  outlineMechanism({ id: "collections", label: "Collections", singular: "collection", plural: "collections", empty: "No collections yet", action: "Create a collection", create: "Collection" }),
  outlineMechanism({ id: "contracts", label: "Contracts", singular: "contract", plural: "contracts", empty: CONTRACT_COPY.groupEmpty, action: CONTRACT_COPY.addAction, create: CONTRACT_COPY.create }),
  outlineMechanism({ id: "tuning", label: "Tuning", singular: "value or rule", plural: "values and rules", empty: "No values or rules yet", action: "Add a value", create: "Value" }),
  outlineMechanism({ id: "time", label: "Time", singular: "clock", plural: "clocks", empty: "No clocks yet", action: "Add a clock", create: "Clock" }),
  outlineMechanism({ id: "direction", label: "Direction", singular: "item", plural: "items", empty: "No moods, palettes, or promises yet", action: "Create a mood", create: "Mood" }),
  outlineMechanism({ id: "sections", label: "Sections", singular: "section", plural: "sections", empty: "No sections yet", action: "Add a chapter", create: "Chapter" }),
  outlineMechanism({ id: "acceptance-tests", label: "Acceptance tests", singular: "acceptance test", plural: "acceptance tests", empty: "No acceptance tests yet", action: "Add an acceptance test", create: "Acceptance test" }),
  outlineMechanism({ id: "personalization", label: "Personalization", singular: "question", plural: "questions", empty: "No questions yet", action: "New question", create: "Question" })
].map(item => [item.id, item])));

export const WIDGET_COPY = Object.freeze({
  brand: "OpenGDD",
  title: "Authoring tool",
  previewVersion: version => `Preview · v${version}`,
  packageControls: "Package controls",
  package: "Package",
  loadingPackages: "Loading packages…",
  newPackage: "New package",
  delete: "Delete",
  packageFile: "Package file",
  importZip: "Import ZIP",
  exportZip: "Export ZIP",
  confirmPackageAction: "Confirm package action",
  packageTitle: "Package title",
  packageId: "Package id",
  createPackage: "Create package",
  cancel: "Cancel",
  packageFiles: "Package files",
  explorerActions: Object.freeze({ newFile: "+ File", newFolder: "+ Folder", rename: "Rename", save: "Save" }),
  loadingPackage: "Loading package…",
  dropZip: "Drop a zip here, or drag an item onto a folder to move it.",
  fileEditor: "File editor",
  openInReader: "Open in reader",
  markdownSource: "Markdown source",
  jsonSource: "JSON source",
  completionResults: "Completion results",
  contextAndValidation: "Context and validation",
  validation: "Validation",
  checkingEllipsis: "Checking…",
  checkingPackage: "Checking package conformance…",
  deleteAction: "Delete",
  outlineLabel: "Outline",
  noFileOpen: "No file open",
  noFileBody: "Create or import a file to begin.",
  binaryAsset: "binary asset",
  binaryAssetBody: "Binary assets are kept in the package but are not previewed here.",
  markdownEditing: "Markdown · editing",
  markdownEditingLarge: "Markdown · editing · wrap off for large file",
  jsonEditing: "JSON · editing",
  jsonEditingLarge: "JSON · editing · wrap off for large file",
  textReadOnly: "text · read only",
  unavailable: "Unavailable",
  validationUnavailable: "Validation unavailable — the conformance schemas could not be loaded.",
  crashed: "Crashed",
  unknownError: "unknown error",
  validationCrashed: message => `Validation crashed: ${message}. The editor is still available.`,
  pass: "PASS",
  passWithWarnings: "PASS WITH WARNINGS",
  fail: "FAIL",
  validationSummary: (verdict, errors, warnings) => `${verdict} · ${errors}E ${warnings}W`,
  validationSummaryFull: (verdict, errors, warnings) => `${verdict} — ${errors} error(s), ${warnings} warning(s)`,
  validationAccessible: text => `Validation ${text}`,
  noFindings: "No findings. This package passes conformance validation.",
  skippedMediaChecks: "Some byte-level media evidence checks were skipped in this browser; the CLI checks them.",
  migrationTitle: "Migration",
  migrationBanner: "This package is written for OpenGDD 0.6 or 0.7. The tool can migrate it to 0.8 — it does the mechanical part and lists what only you can decide.",
  previewMigration: "Preview the migration",
  preparingMigration: "Preparing the migration preview…",
  migrationChanges: "Files the tool will change",
  migrationManual: "Only you can decide these",
  migrationRefused: "The migration would leave errors behind, so nothing was changed. Fix these and try again.",
  migrationNoOp: "Nothing to migrate.",
  dismissMigrationNoOp: "Dismiss",
  applyMigration: "Apply migration",
  notNow: "Not now",
  migrationUndo: "Migrate to OpenGDD 0.8",
  migrationAfter: "Left for you after migration",
  dismissMigrationManual: "Dismiss this list",
  migrationPreviewFailed: "The migration preview could not run.",
  migrationChanged: "The package changed while the preview was being prepared. Preview it again.",
  migrationStale: "The package changed since you looked; here is the new list.",
  migrationSchemaUnavailable: "This host did not supply `clocks.schema.json`, so the migration cannot be checked here; run `npx opengdd migrate` instead.",
  migrationNoOutputs: "There are no file changes to apply. Nothing was changed.",
  migrationUnsafeOutput: "This preview contains a file change the tool cannot apply safely. Nothing was changed.",
  migrationBinaryOutput: path => `The preview would replace \`${path}\`, but this package has it as a binary file. Nothing was changed.`,
  migrationCreated: "created",
  migrationRewritten: "rewritten",
  value: "Value",
  packageName: "package name",
  matches: count => `${count} match${count === 1 ? "" : "es"}`,
  narrowedMatches: (visible, total) => `${visible} of ${total} matches — keep typing to narrow`,
  completionAction: name => `Complete ${name}`,
  checkingOnPageFallback: "Checking on this page — large packages may briefly pause editing",
  openedPackage: title => `Opened ${title}.`,
  exportedPackage: name => `Exported ${name}.`,
  protectedRename: name => `This name belongs to the OpenGDD package. Keep it as ${name}, or create a new file.`,
  protectedDelete: name => `This file belongs to the OpenGDD package. Keep ${name}, or clear its contents.`,
  protectedDeleteConfirm: Object.freeze({
    "direction.json": "Deleting direction.json switches off art direction for this package.",
    "personalization.json": "Deleting personalization.json switches off build personalization for this package.",
    "clocks.json": "Deleting clocks.json switches off declared time modes and clocks for this package."
  }),
  packageRelativePath: "Use a package-relative path without . or .. segments.",
  notWritableText: path => `${path} is not writable text.`,
  jsonObjectRequired: path => `${path} must contain a JSON object.`,
  editProse: "Edit prose",
  moveAction: path => `Move ${path}`,
  deletePathAction: path => `Delete ${path}`,
  createPathAction: path => `Create ${path}`,
  renamePathAction: path => `Rename ${path}`,
  newFilePath: "New file path",
  newFolderPath: "New folder path",
  newPath: "New path",
  defaultFilePath: "notes.md",
  defaultFolderPath: "folder",
  pathExists: path => `A package item already exists at ${path}.`,
  folderInsideItself: "A folder cannot be moved inside itself.",
  destinationNotEmpty: path => `The destination ${path} is not empty.`,
  renameLeafOnly: "Rename only the selected item's name, not its parent path.",
  resetExample: "Reset to the original files",
  resetExampleLabel: "Reset to the original files",
  deleteLocalPackage: "Delete local package",
  noPackages: "No packages yet",
  choosePackage: "Choose a package",
  importedPackage: title => `Imported ${title} and saved it in this browser.`,
  declarationGone: name => `${name} is no longer declared`,
  thisDeclaration: "This declaration",
  resetPackageLabel: title => `Reset ${title} to the original files`,
  deletePackageLabel: title => `Delete package: ${title}`,
  resetQuestion: title => `Reset ${title}?`,
  deleteQuestion: title => `Delete ${title}?`,
  yesReset: "Yes, reset to the original files",
  yesDelete: "Yes, delete",
  exampleReset: "Restored the original files.",
  localPackageDeleted: "Local package deleted.",
  enterPackageIdentity: "Enter a title and a kebab-case package id.",
  duplicatePackageId: id => `A package already uses the id ${id}. Choose another id, or delete the local package first.`,
  createdPackage: title => `Created ${title} and saved it in this browser.`,
  packageSaveFailure: message => `The package was created but could not be saved: ${message}`,
  browserPackagesUnavailable: message => `Browser packages are unavailable: ${message}`,
  selectedPackageOpenFailure: message => `The selected package could not be opened: ${message}`,
  exampleUnavailable: message => `The listed package is unavailable: ${message}`,
  createOrImport: "Create a package or import a ZIP to begin.",
  untitledGame: "Untitled Game",
  untitledGameTitle: "Untitled game",
  noPackageSelected: "No package selected",
  fileCount: count => `${count} files`,
  nameCount: count => `${count} names`,
  classifiedCount: (count, classification) => `${count} ${classification}`,
  validationPending: "validation pending",
  validationUnavailableStatus: "validation unavailable",
  problemCounts: (total, errors, warnings) => `${total} problems — ${errors} errors, ${warnings} warnings`,
  problemRow: (severity, message) => `${severity === "error" ? "Error" : "Warning"}: ${message}`,
  addRecord: "Add a record",
  linkOffer: (field, drawer) => `\`${field}\` looks like links to \`${drawer}\`. Describe it as a link?`,
  noFieldForm: field => `\`${field}\` has no field form yet; describe the fields by hand first`,
  describeLinkUndo: field => `Describe ${field} as a link`,
  stagedWriteUnavailable: "This change could not be validated, so it was not written.",
  line: number => `line ${number}`,
  outlineMechanisms: OUTLINE_MECHANISMS,
  tuningRulesBranch: "rules",
  outlineNothing: "Nothing declared yet",
  outlineNothingAction: "Add a chapter",
  outlineSelected: (name, panelTitle) => `${name} selected, ${panelTitle} open`,
  showInFile: INSPECTOR_COPY.showInFile,
  noValidationProblems: "No validation problems",
  create: "Create",
  problemsOnly: "Problems only"
});
