export const WORKBENCH_COPY = Object.freeze({
  explorer: "File explorer",
  prose: "Prose editor",
  outline: "Outline",
  inspector: "Inspector",
  noPackageFiles: "No package files yet",
  createMinimalPackage: "Create a minimal package",
  nothingDeclared: "Nothing declared yet",
  createIdentifier: "Create a pillar",
  nothingSelected: "Nothing selected",
  collapsePanel: label => `Collapse ${label.toLowerCase()}`,
  resizePanel: label => `Resize ${label}`,
  collapsedColumns: "Collapsed columns",
  openExplorer: "Open file explorer",
  openOutline: "Open outline",
  openInspector: "Open inspector",
  backToText: "Back to your text",
  persistenceDenied: "This browser may clear this draft when space is low. Export a ZIP to keep a copy.",
  theme: "Theme",
  themes: Object.freeze(["Light", "Dark", "System"]),
  packageStatus: "Package status",
  errorsPending: "Errors: —",
  warningsPending: "Warnings: —",
  validationChecking: "checking",
  validationUnavailable: "unavailable",
  validationStopped: "stopped",
  validationDone: "done",
  errors: count => `Errors: ${count}`,
  warnings: count => `Warnings: ${count}`,
  words: count => `Words: ${count}`,
  declarations: count => `Declarations: ${count}`,
  checkingInWorker: "Checking in worker",
  checkingOnPage: "Checking on this page",
  validationStatus: state => `Validation: ${state}`,
  storageStatus: state => `Files stay in this browser, nothing is uploaded · ${state}`,
  storageProtected: "storage protected",
  storageMayBeCleared: "storage may be cleared",
  notSaved: "Not saved",
  version: (tool, spec) => `v${tool} · OpenGDD ${spec}`,
  undoHistory: "Undo history",
  undoAction: action => `Undo ${action}`,
  nothingToUndo: "Nothing to undo",
  undoHelp: "Undo reaches back 200 actions. Continuous typing may count as one action; older work is still safe in the file.",
  newFile: "New file",
  newFolder: "New folder",
  coldNew: "New package from a minimal template",
  coldPackage: title => title ? `Open ${title}` : "Open package",
  chooseHowToBegin: "Choose how to begin.",
  narrowTitle: "This screen is too narrow for the workbench",
  narrowAction: "Make the window at least 760 pixels wide"
});
